# .travis.yml

branches:
  only:
    - master

before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

jobs:
  include:
    # Removing section due to already being initialised
    # - stage: Bootstrap account
    #   script:
    #     - make terraform-bootstrap env=global

    - stage: Deploy Dev
      script:
        - make terraform-bastion-host env=dev
    
    - stage: Deploy Bastion-host
      if: branch = master AND tag =~ ^release
      script:
        - make terraform-bastion-host env=prod
